name       : yelp-tools
version    : 3.32.1
release    : 7
source     :
    - https://download.gnome.org/sources/yelp-tools/3.32/yelp-tools-3.32.1.tar.xz : 99a7c312a5fcb427870dc198af02801eb0f8ea63317e20110fc0303eb44636e3
license    : GPL-2.0-or-later
component  : desktop.gnome.doc
summary    : Tools to create Yelp documentation
description: |
    Yelp-tools is a collection of scripts and build utilities to help create,
    manage, and publish documentation for Yelp and the web. Most of the heavy
    lifting is done by packages like yelp-xsl and itstool. This package just
    wraps things up in a developer-friendly way.
patterns   : /
replaces   :
    - yelp-tools-devel
builddeps  :
    - pkgconfig(yelp-xsl)
    - itstool
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
