name       : yelp-tools
version    : 3.32.0
release    : 6
source     :
    - https://download.gnome.org/sources/yelp-tools/3.32/yelp-tools-3.32.0.tar.xz : bfdd40d10d837d1a170c7fe70b3436d30e6698db809d5be459ea0f7fbb69ee0c
license    : GPL-2.0-or-later
component  : desktop.gnome.doc
summary    : Tools to create Yelp documentation
description: |
    Yelp-tools is a collection of scripts and build utilities to help create,
    manage, and publish documentation for Yelp and the web. Most of the heavy
    lifting is done by packages like yelp-xsl and itstool. This package just
    wraps things up in a developer-friendly way.
patterns   : /
replaces   :
    - yelp-tools-devel
builddeps  :
    - pkgconfig(yelp-xsl)
    - itstool
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
