name       : yelp-tools
version    : '41.0'
release    : 13
source     :
    - https://download.gnome.org/sources/yelp-tools/41/yelp-tools-41.0.tar.xz : 37f1acc02bcbe68a31b86e07c129a839bd3276e656dc89eb7fc0a92746eff272
license    : GPL-2.0-or-later
component  : desktop.gnome.doc
summary    : Tools to create Yelp documentation
description: |
    Yelp-tools is a collection of scripts and build utilities to help create, manage, and publish documentation for Yelp and the web. Most of the heavy lifting is done by packages like yelp-xsl and itstool. This package just wraps things up in a developer-friendly way.
patterns   : /
replaces   :
    - yelp-tools-devel
builddeps  :
    - pkgconfig(yelp-xsl)
    - docbook-xml
    - itstool
    - python-configparser
    - python-lxml
rundeps    :
    - python-configparser
    - python-lxml
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
