name       : yelp-tools
version    : 3.38.0
release    : 11
source     :
    - https://download.gnome.org/sources/yelp-tools/3.38/yelp-tools-3.38.0.tar.xz : 607ce4b3ee8517c42db924a01a78660a03317595c75825731ea86a920e2b04b0
license    : GPL-2.0-or-later
component  : desktop.gnome.doc
summary    : Tools to create Yelp documentation
description: |
    Yelp-tools is a collection of scripts and build utilities to help create, manage, and publish documentation for Yelp and the web. Most of the heavy lifting is done by packages like yelp-xsl and itstool. This package just wraps things up in a developer-friendly way.
patterns   : /
replaces   :
    - yelp-tools-devel
builddeps  :
    - pkgconfig(yelp-xsl)
    - itstool
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
