name       : yelp-tools
version    : 3.18.0
release    : 2
source     :
    - http://ftp.gnome.org/pub/gnome/sources/yelp-tools/3.18/yelp-tools-3.18.0.tar.xz : c6c1d65f802397267cdc47aafd5398c4b60766e0a7ad2190426af6c0d0716932
license    : GPL-2.0
component  : desktop.gnome.doc
summary    : Tools to create Yelp documentation
description: |
    Yelp-tools is a collection of scripts and build utilities to help create,
    manage, and publish documentation for Yelp and the web. Most of the heavy
    lifting is done by packages like yelp-xsl and itstool. This package just
    wraps things up in a developer-friendly way.
builddeps  :
    - pkgconfig(yelp-xsl)
    - itstool
    - docbook-xml
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
